### PR TITLE
COM

### PR DESCRIPTION
**Pull request by ghost**
我也不知道我写了什么东西出来。
qnmd小学期。

### CODE REVIEW

**Comment by TessyKing** [comment]
先睡觉啦～
晚安浅韵xjj
明天我和刘洁把我俩的一接
再找朱明朗要她负责的部分
再和老师沟通沟通“历史数据”到底是啥
再安抚一下老孙
哦 不是明天 是今天




| |
jzh010201
|
|
***@***.***
|

Signature is customized by Netease Mail Master

On 08/29/2021 01:25, Qianyun wrote:

Closed #2.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghost** [comment]
PR again.

added COM features.

**Comment by Lovely-Qianyun** [comment]
Finished by others.

**Comment by ghost** [comment]
Finished by others.

**Pull request closed without merging**
